before_script:
  - touch application/config.sql
  - touch application/modules.sql
  - mysql -u travis -e 'CREATE DATABASE StoredProcedureWeb;'
  - mysql -u travis -D StoredProcedureWeb < install.sql
script: mysql -u travis -D StoredProcedureWeb -e 'CALL sqlunit$execute; CALL sqlunit$results; CALL sqlunit$coverage;'
